In [83]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso

In [65]:
traindf = pd.read_csv('../data/preprocessed/train_preprocessed.csv') #Đọc dữ liệu từ tập huấn luyện đã qua xử lí
traindf = traindf.rename(columns={'Unnamed: 0': 'Id'}) #Thêm tên cho cột Id
traindf


Id  MSSubClass  MSZoning  LotFrontage   LotArea    Street  LotShape  \
0        1    0.073375 -0.045532    -0.226101 -0.207142  0.064238  0.750731   
1        2   -0.872563 -0.045532     0.455190 -0.091886  0.064238  0.750731   
2        3    0.073375 -0.045532    -0.089843  0.073480  0.064238 -1.378933   
3        4    0.309859 -0.045532    -0.453198 -0.096897  0.064238 -1.378933   
4        5    0.073375 -0.045532     0.636868  0.375148  0.064238 -1.378933   
...    ...         ...       ...          ...       ...       ...       ...   
1455  1456    0.073375 -0.045532    -0.362359 -0.260560  0.064238  0.750731   
1456  1457   -0.872563 -0.045532     0.682287  0.266407  0.064238  0.750731   
1457  1458    0.309859 -0.045532    -0.180681 -0.147810  0.064238  0.750731   
1458  1459   -0.872563 -0.045532    -0.089843 -0.080160  0.064238  0.750731   
1459  1460   -0.872563 -0.045532     0.228093 -0.058112  0.064238  0.750731   

      LandContour  Utilities  LotConfig  ...  EnclosedPorch  3SsnPorch  \
0        0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1        0.314667   -0.02618  -0.628316  ...      -0.359325  -0.116339   
2        0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
3        0.314667   -0.02618  -1.861302  ...       4.092524  -0.116339   
4        0.314667   -0.02618  -0.628316  ...      -0.359325  -0.116339   
...           ...        ...        ...  ...            ...        ...   
1455     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1456     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1457     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1458     0.314667   -0.02618   0.604670  ...       1.473789  -0.116339   
1459     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   

      ScreenPorch  PoolArea   MiscVal    MoSold    YrSold  SaleType  \
0       -0.270208 -0.068692 -0.087688 -1.599111  0.138777  0.313867   
1       -0.270208 -0.068692 -0.087688 -0.489110 -0.614439  0.313867   
2       -0.270208 -0.068692 -0.087688  0.990891  0.138777  0.313867   
3       -0.270208 -0.068692 -0.087688 -1.599111 -1.367655  0.313867   
4       -0.270208 -0.068692 -0.087688  2.100892  0.138777  0.313867   
...           ...       ...       ...       ...       ...       ...   
1455    -0.270208 -0.068692 -0.087688  0.620891 -0.614439  0.313867   
1456    -0.270208 -0.068692 -0.087688 -1.599111  1.645210  0.313867   
1457    -0.270208 -0.068692  4.953112 -0.489110  1.645210  0.313867   
1458    -0.270208 -0.068692 -0.087688 -0.859110  1.645210  0.313867   
1459    -0.270208 -0.068692 -0.087688 -0.119110  0.138777  0.313867   

      SaleCondition  SalePrice  
0          0.208502   0.347273  
1          0.208502   0.007288  
2          0.208502   0.536154  
3         -3.426284  -0.515281  
4          0.208502   0.869843  
...             ...        ...  
1455       0.208502  -0.074560  
1456       0.208502   0.366161  
1457       0.208502   1.077611  
1458       0.208502  -0.488523  
1459       0.208502  -0.420841  

[1460 rows x 77 columns]

In [66]:
features = traindf.drop(columns = ['Id', 'SalePrice']) #Bỏ 2 cột Id và SalePrice để lấy dataframe gồm những đặc điểm
labels = traindf['SalePrice'] #Lấy cột SalePrice để huấn luyện
features

MSSubClass  MSZoning  LotFrontage   LotArea    Street  LotShape  \
0       0.073375 -0.045532    -0.226101 -0.207142  0.064238  0.750731   
1      -0.872563 -0.045532     0.455190 -0.091886  0.064238  0.750731   
2       0.073375 -0.045532    -0.089843  0.073480  0.064238 -1.378933   
3       0.309859 -0.045532    -0.453198 -0.096897  0.064238 -1.378933   
4       0.073375 -0.045532     0.636868  0.375148  0.064238 -1.378933   
...          ...       ...          ...       ...       ...       ...   
1455    0.073375 -0.045532    -0.362359 -0.260560  0.064238  0.750731   
1456   -0.872563 -0.045532     0.682287  0.266407  0.064238  0.750731   
1457    0.309859 -0.045532    -0.180681 -0.147810  0.064238  0.750731   
1458   -0.872563 -0.045532    -0.089843 -0.080160  0.064238  0.750731   
1459   -0.872563 -0.045532     0.228093 -0.058112  0.064238  0.750731   

      LandContour  Utilities  LotConfig  LandSlope  ...  OpenPorchSF  \
0        0.314667   -0.02618   0.604670  -0.225716  ...     0.216503   
1        0.314667   -0.02618  -0.628316  -0.225716  ...    -0.704483   
2        0.314667   -0.02618   0.604670  -0.225716  ...    -0.070361   
3        0.314667   -0.02618  -1.861302  -0.225716  ...    -0.176048   
4        0.314667   -0.02618  -0.628316  -0.225716  ...     0.563760   
...           ...        ...        ...        ...  ...          ...   
1455     0.314667   -0.02618   0.604670  -0.225716  ...    -0.100558   
1456     0.314667   -0.02618   0.604670  -0.225716  ...    -0.704483   
1457     0.314667   -0.02618   0.604670  -0.225716  ...     0.201405   
1458     0.314667   -0.02618   0.604670  -0.225716  ...    -0.704483   
1459     0.314667   -0.02618   0.604670  -0.225716  ...     0.322190   

      EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea   MiscVal    MoSold  \
0         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
1         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -0.489110   
2         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  0.990891   
3          4.092524  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
4         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  2.100892   
...             ...        ...          ...       ...       ...       ...   
1455      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  0.620891   
1456      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
1457      -0.359325  -0.116339    -0.270208 -0.068692  4.953112 -0.489110   
1458       1.473789  -0.116339    -0.270208 -0.068692 -0.087688 -0.859110   
1459      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -0.119110   

        YrSold  SaleType  SaleCondition  
0     0.138777  0.313867       0.208502  
1    -0.614439  0.313867       0.208502  
2     0.138777  0.313867       0.208502  
3    -1.367655  0.313867      -3.426284  
4     0.138777  0.313867       0.208502  
...        ...       ...            ...  
1455 -0.614439  0.313867       0.208502  
1456  1.645210  0.313867       0.208502  
1457  1.645210  0.313867       0.208502  
1458  1.645210  0.313867       0.208502  
1459  0.138777  0.313867       0.208502  

[1460 rows x 75 columns]

In [67]:
testdf = pd.read_csv('../data/preprocessed/test_preprocessed.csv') #Đọc dữ liệu từ tập kiểm tra đã qua xử lí
test = testdf.drop(columns = ['Id']) #Bỏ cột Id để kiểm tra

In [68]:
raw = pd.read_csv('../data/raw/train.csv') #Đọc dữ liệu từ tập huấn luyện gốc
mean = raw['SalePrice'].mean() #Giá trị trung bình của SalePrice
std = raw['SalePrice'].std() #Độ lệch chuẩn của SalePrice

## Linear Regression

In [69]:
#Huấn luyện mô hình với hồi quy tuyến tính
LinearRegr = LinearRegression()
LinearRegr.fit(features, labels)

LinearRegression()

In [70]:
LinearRegr.predict(test) #Dự đoán kết quả, tuy nhiên đây không phải SalePrice thật sự

array([-0.94749952, -0.33022001, -0.18269322, ..., -0.39958445,
       -0.73403882,  0.79649017])

In [71]:
#Tạo dataframe với hàm apply cho từng phần tử của Predict(test) thành SalePrice thật sự
SalePrice1 = pd.DataFrame(LinearRegr.predict(test), columns = ['SalePrice']).apply(lambda x: x*std + mean) 

In [ ]:
Id1 = pd.DataFrame(testdf['Id']) #Tạo dataframe cho Id
output = pd.concat([Id1, SalePrice1], axis = 1) #Kết hợp 2 dataframe

Id      SalePrice
0     1461  105649.462572
1     1462  154687.691759
2     1463  166407.589360
3     1464  183123.326247
4     1465  187566.933616
...    ...            ...
1454  2915   72858.759739
1455  2916   60257.143217
1456  2917  149177.207203
1457  2918  122607.314692
1458  2919  244196.368879

[1459 rows x 2 columns]

In [86]:
#Lưu kết quả
output_dir = './data/output'
os.makedirs(output_dir, exist_ok=True)
output_filepath = os.path.join(output_dir, 'LinearRegr_predictions.csv')
output.to_csv(output_filepath, index=False)


In [87]:
print(f"Predictions saved to {output_filepath}")

Predictions saved to ./data/output\LinearRegr_predictions.csv


## Ridge Regression

In [73]:
#Huấn luyện mô hình với hồi quy Ridge
RidgeRegr = Ridge(alpha=10)
RidgeRegr.fit(features, labels)

Ridge(alpha=10)

In [74]:
RidgeRegr.predict(test)

array([-0.94199083, -0.33407856, -0.17822429, ..., -0.39077502,
       -0.74097702,  0.79412926])

In [75]:
SalePrice2 = pd.DataFrame(RidgeRegr.predict(test), columns = ['SalePrice']).apply(lambda x: x*std + mean) 

In [84]:
Id2 = pd.DataFrame(testdf['Id'])
pd.concat([Id2, SalePrice2], axis = 1)

Id      SalePrice
0     1461  106087.086434
1     1462  154381.158747
2     1463  166762.612601
3     1464  183567.340192
4     1465  187674.424508
...    ...            ...
1454  2915   72898.794974
1455  2916   60805.249234
1456  2917  149877.050242
1457  2918  122056.126459
1458  2919  244008.811636

[1459 rows x 2 columns]

## Lasso Regression

In [77]:
#Huấn luyện mô hình với hồi quy Lasso
LassoRegr = Lasso(alpha = 0.001)
LassoRegr.fit(features, labels)

Lasso(alpha=0.001)

In [ ]:
LassoRegr.predict(test)

array([-0.93203818, -0.30556796, -0.17875908, ..., -0.39477137,
       -0.77037206,  0.78456689])

In [79]:
SalePrice3 = pd.DataFrame(LassoRegr.predict(test), columns = ['SalePrice']).apply(lambda x: x*std + mean)

In [80]:
Id3 = pd.DataFrame(testdf['Id']) 
pd.concat([Id3, SalePrice3], axis = 1) 

Id      SalePrice
0     1461  106877.749720
1     1462  156646.112703
2     1463  166720.127292
3     1464  183423.853862
4     1465  188317.377159
...    ...            ...
1454  2915   72378.009396
1455  2916   61058.714525
1456  2917  149559.570542
1457  2918  119720.911306
1458  2919  243249.153320

[1459 rows x 2 columns]