In [38]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [39]:
traindf = pd.read_csv('../data/preprocessed/train_preprocessed.csv')
traindf = traindf.rename(columns={'Unnamed: 0': 'Id'})
traindf


Id  MSSubClass  MSZoning  LotFrontage   LotArea    Street  LotShape  \
0        1    0.073375 -0.045532    -0.226101 -0.207142  0.064238  0.750731   
1        2   -0.872563 -0.045532     0.455190 -0.091886  0.064238  0.750731   
2        3    0.073375 -0.045532    -0.089843  0.073480  0.064238 -1.378933   
3        4    0.309859 -0.045532    -0.453198 -0.096897  0.064238 -1.378933   
4        5    0.073375 -0.045532     0.636868  0.375148  0.064238 -1.378933   
...    ...         ...       ...          ...       ...       ...       ...   
1455  1456    0.073375 -0.045532    -0.362359 -0.260560  0.064238  0.750731   
1456  1457   -0.872563 -0.045532     0.682287  0.266407  0.064238  0.750731   
1457  1458    0.309859 -0.045532    -0.180681 -0.147810  0.064238  0.750731   
1458  1459   -0.872563 -0.045532    -0.089843 -0.080160  0.064238  0.750731   
1459  1460   -0.872563 -0.045532     0.228093 -0.058112  0.064238  0.750731   

      LandContour  Utilities  LotConfig  ...  EnclosedPorch  3SsnPorch  \
0        0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1        0.314667   -0.02618  -0.628316  ...      -0.359325  -0.116339   
2        0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
3        0.314667   -0.02618  -1.861302  ...       4.092524  -0.116339   
4        0.314667   -0.02618  -0.628316  ...      -0.359325  -0.116339   
...           ...        ...        ...  ...            ...        ...   
1455     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1456     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1457     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   
1458     0.314667   -0.02618   0.604670  ...       1.473789  -0.116339   
1459     0.314667   -0.02618   0.604670  ...      -0.359325  -0.116339   

      ScreenPorch  PoolArea   MiscVal    MoSold    YrSold  SaleType  \
0       -0.270208 -0.068692 -0.087688 -1.599111  0.138777  0.313867   
1       -0.270208 -0.068692 -0.087688 -0.489110 -0.614439  0.313867   
2       -0.270208 -0.068692 -0.087688  0.990891  0.138777  0.313867   
3       -0.270208 -0.068692 -0.087688 -1.599111 -1.367655  0.313867   
4       -0.270208 -0.068692 -0.087688  2.100892  0.138777  0.313867   
...           ...       ...       ...       ...       ...       ...   
1455    -0.270208 -0.068692 -0.087688  0.620891 -0.614439  0.313867   
1456    -0.270208 -0.068692 -0.087688 -1.599111  1.645210  0.313867   
1457    -0.270208 -0.068692  4.953112 -0.489110  1.645210  0.313867   
1458    -0.270208 -0.068692 -0.087688 -0.859110  1.645210  0.313867   
1459    -0.270208 -0.068692 -0.087688 -0.119110  0.138777  0.313867   

      SaleCondition  SalePrice  
0          0.208502   0.347273  
1          0.208502   0.007288  
2          0.208502   0.536154  
3         -3.426284  -0.515281  
4          0.208502   0.869843  
...             ...        ...  
1455       0.208502  -0.074560  
1456       0.208502   0.366161  
1457       0.208502   1.077611  
1458       0.208502  -0.488523  
1459       0.208502  -0.420841  

[1460 rows x 77 columns]

In [40]:
features = traindf.drop(columns = ['Id', 'SalePrice'])
labels = traindf['SalePrice']
features

MSSubClass  MSZoning  LotFrontage   LotArea    Street  LotShape  \
0       0.073375 -0.045532    -0.226101 -0.207142  0.064238  0.750731   
1      -0.872563 -0.045532     0.455190 -0.091886  0.064238  0.750731   
2       0.073375 -0.045532    -0.089843  0.073480  0.064238 -1.378933   
3       0.309859 -0.045532    -0.453198 -0.096897  0.064238 -1.378933   
4       0.073375 -0.045532     0.636868  0.375148  0.064238 -1.378933   
...          ...       ...          ...       ...       ...       ...   
1455    0.073375 -0.045532    -0.362359 -0.260560  0.064238  0.750731   
1456   -0.872563 -0.045532     0.682287  0.266407  0.064238  0.750731   
1457    0.309859 -0.045532    -0.180681 -0.147810  0.064238  0.750731   
1458   -0.872563 -0.045532    -0.089843 -0.080160  0.064238  0.750731   
1459   -0.872563 -0.045532     0.228093 -0.058112  0.064238  0.750731   

      LandContour  Utilities  LotConfig  LandSlope  ...  OpenPorchSF  \
0        0.314667   -0.02618   0.604670  -0.225716  ...     0.216503   
1        0.314667   -0.02618  -0.628316  -0.225716  ...    -0.704483   
2        0.314667   -0.02618   0.604670  -0.225716  ...    -0.070361   
3        0.314667   -0.02618  -1.861302  -0.225716  ...    -0.176048   
4        0.314667   -0.02618  -0.628316  -0.225716  ...     0.563760   
...           ...        ...        ...        ...  ...          ...   
1455     0.314667   -0.02618   0.604670  -0.225716  ...    -0.100558   
1456     0.314667   -0.02618   0.604670  -0.225716  ...    -0.704483   
1457     0.314667   -0.02618   0.604670  -0.225716  ...     0.201405   
1458     0.314667   -0.02618   0.604670  -0.225716  ...    -0.704483   
1459     0.314667   -0.02618   0.604670  -0.225716  ...     0.322190   

      EnclosedPorch  3SsnPorch  ScreenPorch  PoolArea   MiscVal    MoSold  \
0         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
1         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -0.489110   
2         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  0.990891   
3          4.092524  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
4         -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  2.100892   
...             ...        ...          ...       ...       ...       ...   
1455      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688  0.620891   
1456      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -1.599111   
1457      -0.359325  -0.116339    -0.270208 -0.068692  4.953112 -0.489110   
1458       1.473789  -0.116339    -0.270208 -0.068692 -0.087688 -0.859110   
1459      -0.359325  -0.116339    -0.270208 -0.068692 -0.087688 -0.119110   

        YrSold  SaleType  SaleCondition  
0     0.138777  0.313867       0.208502  
1    -0.614439  0.313867       0.208502  
2     0.138777  0.313867       0.208502  
3    -1.367655  0.313867      -3.426284  
4     0.138777  0.313867       0.208502  
...        ...       ...            ...  
1455 -0.614439  0.313867       0.208502  
1456  1.645210  0.313867       0.208502  
1457  1.645210  0.313867       0.208502  
1458  1.645210  0.313867       0.208502  
1459  0.138777  0.313867       0.208502  

[1460 rows x 75 columns]

In [41]:
testdf = pd.read_csv('../data/preprocessed/test_preprocessed.csv')
test = testdf.drop(columns = ['Id'])

## Linear Regression

In [42]:
from sklearn.linear_model import LinearRegression

In [43]:
LinearRegr = LinearRegression()
LinearRegr.fit(features, labels)

LinearRegression()

In [44]:
LinearRegr.predict(test)

array([-0.94749952, -0.33022001, -0.18269322, ..., -0.39958445,
       -0.73403882,  0.79649017])

## Ridge Regression

In [45]:
from sklearn.linear_model import Ridge

In [46]:
RidgeRegr = Ridge(alpha=10)
RidgeRegr.fit(features, labels)

Ridge(alpha=10)

In [47]:
RidgeRegr.predict(test)

array([-0.94199083, -0.33407856, -0.17822429, ..., -0.39077502,
       -0.74097702,  0.79412926])

## Lasso Regression

In [48]:
from sklearn.linear_model import Lasso

In [49]:
LassoRegr = Lasso(alpha = 0.001)
LassoRegr.fit(features, labels)

Lasso(alpha=0.001)

In [50]:
LassoRegr.predict(test)

array([-0.93203818, -0.30556796, -0.17875908, ..., -0.39477137,
       -0.77037206,  0.78456689])